apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: gfw
  name: analysis-gee
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: analysis-gee
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
